// @title Auto Messaging API
// @version 1.0
// @description This is a REST API for automatic message processing
// @termsOfService http://swagger.io/terms/

// @contact.name API Support
// @contact.url http://www.swagger.io/support
// @contact.email support@swagger.io

// @license.name Apache 2.0
// @license.url http://www.apache.org/licenses/LICENSE-2.0.html

// @host localhost:8080
// @BasePath /api/v1
// @schemes http

package main

import (
	"auto-messaging/config"
	_ "auto-messaging/docs" // docs is generated by Swag CLI
	"auto-messaging/internal/client"
	"auto-messaging/internal/controller"
	"auto-messaging/internal/handler"
	"auto-messaging/internal/repository"
	"auto-messaging/internal/router"
	"auto-messaging/pkg/cache"
	"log"
	"os"
	"os/signal"
	"strconv"
	"syscall"

	swaggerFiles "github.com/swaggo/files"
	ginSwagger "github.com/swaggo/gin-swagger"
)

// @title Auto Messaging API
// @version 1.0
// @description This is a REST API for automatic message processing
// @termsOfService http://swagger.io/terms/

// @contact.name API Support
// @contact.url http://www.swagger.io/support
// @contact.email support@swagger.io

// @license.name Apache 2.0
// @license.url http://www.apache.org/licenses/LICENSE-2.0.html

// @host localhost:8080
// @BasePath /api/v1
// @schemes http

func main() {
	// Initialize logger
	logger := log.New(os.Stdout, "", log.LstdFlags)

	// Load configuration
	cfg, err := config.Load()
	if err != nil {
		logger.Fatalf("Failed to load config: %v", err)
	}

	// Initialize database
	if _, err := repository.InitDB(cfg.Database); err != nil {
		logger.Fatalf("Failed to initialize database: %v", err)
	}

	// Initialize cache
	messageCache := cache.NewRedisCache(
		cfg.Redis.Host,
		cfg.Redis.Port,
		cfg.Redis.Password,
		cfg.Redis.DB,
	)

	// Initialize webhook client
	webhookClient := client.NewWebhookClient(cfg.Webhook.URL, cfg.Webhook.AuthKey)

	// Initialize repository
	messageRepo := repository.NewMessageRepository()

	// Initialize controller
	messageController := controller.NewMessageController(messageRepo, webhookClient, messageCache, logger)

	// Initialize handlers
	messageHandler := handler.NewMessageHandler(messageController)

	// Setup router
	r := router.SetupRouter(messageHandler)

	// Add Swagger
	r.GET("/swagger/*any", ginSwagger.WrapHandler(swaggerFiles.Handler))

	// Start server
	logger.Printf("Server starting on port %d", cfg.Server.Port)

	// Start server in a goroutine
	go func() {
		if err := r.Run(":" + strconv.Itoa(cfg.Server.Port)); err != nil {
			logger.Fatalf("Failed to start server: %v", err)
		}
	}()

	// Wait for interrupt signal to gracefully shutdown the server
	quit := make(chan os.Signal, 1)
	signal.Notify(quit, syscall.SIGINT, syscall.SIGTERM)
	<-quit
	logger.Println("Shutting down server...")
}
