basePath: /api/v1
definitions:
  controller.CreateMessageRequest:
    properties:
      content:
        type: string
      scheduled_time:
        type: string
      to:
        type: string
    required:
    - content
    - scheduled_time
    - to
    type: object
  controller.ErrorResponse:
    properties:
      error:
        type: string
    type: object
  controller.MessageResponse:
    properties:
      message:
        type: string
    type: object
  model.Message:
    properties:
      content:
        type: string
      created_at:
        type: string
      id:
        type: integer
      scheduled_time:
        type: string
      sent_at:
        type: string
      status:
        type: string
      to:
        type: string
      updated_at:
        type: string
    type: object
host: localhost:8080
info:
  contact:
    email: support@swagger.io
    name: API Support
    url: http://www.swagger.io/support
  description: This is a REST API for automatic message processing
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: Auto Messaging API
  version: "1.0"
paths:
  /api/v1/messaging/sent:
    get:
      consumes:
      - application/json
      description: Get a list of all sent messages
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/model.Message'
            type: array
      summary: Get sent messages
      tags:
      - messages
  /api/v1/messaging/start:
    post:
      consumes:
      - application/json
      description: Start the automatic message sending process
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Start automatic message sending
      tags:
      - messages
  /api/v1/messaging/stop:
    post:
      consumes:
      - application/json
      description: Stop the automatic message sending process
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Stop automatic message sending
      tags:
      - messages
  /messages:
    get:
      description: Get a list of all messages
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/model.Message'
            type: array
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/controller.ErrorResponse'
      summary: Get all messages
      tags:
      - messages
    post:
      consumes:
      - application/json
      description: Create a new message with the provided details
      parameters:
      - description: Message details
        in: body
        name: message
        required: true
        schema:
          $ref: '#/definitions/controller.CreateMessageRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/model.Message'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/controller.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/controller.ErrorResponse'
      summary: Create a new message
      tags:
      - messages
  /messages/{id}:
    delete:
      description: Delete a message by its ID
      parameters:
      - description: Message ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "204":
          description: No Content
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/controller.ErrorResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/controller.ErrorResponse'
      summary: Delete a message
      tags:
      - messages
    get:
      description: Get a message by its ID
      parameters:
      - description: Message ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.Message'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/controller.ErrorResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/controller.ErrorResponse'
      summary: Get a message by ID
      tags:
      - messages
    put:
      consumes:
      - application/json
      description: Update an existing message
      parameters:
      - description: Message ID
        in: path
        name: id
        required: true
        type: integer
      - description: Updated message details
        in: body
        name: message
        required: true
        schema:
          $ref: '#/definitions/controller.CreateMessageRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.Message'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/controller.ErrorResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/controller.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/controller.ErrorResponse'
      summary: Update a message
      tags:
      - messages
  /messaging/start:
    post:
      description: Start processing pending messages
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/controller.MessageResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/controller.ErrorResponse'
      summary: Start message processing
      tags:
      - messaging
  /messaging/stop:
    post:
      description: Stop processing messages
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/controller.MessageResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/controller.ErrorResponse'
      summary: Stop message processing
      tags:
      - messaging
schemes:
- http
swagger: "2.0"
